apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80
    targetPort: http-web-svc
  - name: dev-port
    protocol: TCP
    port: 8888
    targetPort: http-web-svc